raw_output = "false"
user_token = ""

[filter]
  limit = "10"
  offset = "0"
  topic = ""

[remotes]
  certs_url = "http://localhost:9019"
  host_url = "http://localhost"
  http_adapter_url = "http://localhost:8008"
  tls_verification = false
  users_url = "http://localhost:9002"